In [113]:
import numpy as np
import hashlib

Name A: Vigdis-Irene Steinsund

Name B:  Thomas Hasvold Adam

In [114]:
#Four (4) 'relevant' TDT4305 sentences

Sentence_1 = "The Big Data platform for students is Blackboard"
Sentence_2 = "Questions on MinHash project by NTNU students is on Piazza"
Sentence_3 = "NTNU Big Data platform are Blackboard and Piazza"
Sentence_4 = "The project data for students are on Blackboard not Piazza"

In [115]:
unique_words =  ['big', 'blackboard', 'data', 'minhash', 'ntnu', 'piazza', 'platform', 'project', 'questions', 'students']# Enter the unique words list here

In [116]:
# User input

print(f"Format: ['word', 'word', 'word' ...] & watch out for white spaces before comma")
user_input = str(input("Enter your created list of unique words: ")) 

f = open("encrypted_dictionary.txt", "r")
encrypted_words = f.read()


# Hash the user input
hashed_user_input = hashlib.sha256(user_input.encode()).hexdigest()

# Compare with the stored hash
if hashed_user_input == encrypted_words:
    print("Correct! Your dictionary matched!")
else:
    print("Incorrect! Try again.")

Format: ['word', 'word', 'word' ...] & watch out for white spaces before comma
Incorrect! Try again.


In [117]:
Input_Matrix = [] # Create an empty array of input matrix

In [128]:
## Compute the values for the input matrix here ##

# Sentences to process
sentences = [
   'big data platform students blackboard',
   "Questions MinHash project NTNU students Piazza",
   "NTNU Big Data platform Blackboard Piazza",
   "project data students Blackboard Piazza"
]

# List of unique words
unique_words = set()

for sentence in sentences: 
    for word in sentence.split(" "):
        unique_words.add(word.lower())

unique_words = sorted(list(unique_words))
print(unique_words)

# Number of unique words and sentences
num_words = len(unique_words)
num_sentences = len(sentences)

# Initialize the input matrix with zeros
input_matrix =  np.full((num_sentences, num_words), 0)

# Compute the values for the input matrix
for j, sentence in enumerate(sentences):    
    for i, word in enumerate(unique_words):
        if word in sentence.lower().split(' '):
            input_matrix[j][i] = 1

print(input_matrix)

['big', 'blackboard', 'data', 'minhash', 'ntnu', 'piazza', 'platform', 'project', 'questions', 'students']
[[1 1 1 0 0 0 1 0 0 1]
 [0 0 0 1 1 1 0 1 1 1]
 [1 1 1 0 1 1 1 0 0 0]
 [0 1 1 0 0 1 0 1 0 1]]


In [147]:
def hash_1(x):
    return ((x + 1) + 3) % 10 + 1

def hash_2(x):
    return (7 * (x + 1) + 1) % 10 + 1

def hash_3(x):
    return (7 * (x + 1) + 2) % 10 + 1

In [148]:

hash_list = [hash_1, hash_2, hash_3]

In [151]:
## Using the hash functions and the input matrix compute the MinHash signature matrix here ##
def minhash(input_matrix, hash_functions):
    # Number of rows and columns in the input matrix
    num_cols, num_rows = input_matrix.shape

    # Number of hash functions
    num_hash_functions = len(hash_functions)

    # Initialize the signature matrix with infinite values
    signature_matrix = np.full((num_cols, num_hash_functions), np.inf)

    # Apply the MinHash algorithm
    for r in range(num_rows):
        for c in range(num_cols):
            if input_matrix[c][r] == 1:
                for i, hash_function in enumerate(hash_functions):
                    hash_value = hash_function(r)
                    print(hash_value)
                    if hash_value < signature_matrix[c][i]:
                        signature_matrix[c][i] = hash_value

    return signature_matrix

In [152]:
print(minhash(input_matrix, hash_list))

5
9
10
5
9
10
6
6
7
6
6
7
6
6
7
7
3
4
7
3
4
7
3
4
8
10
1
9
7
8
9
7
8
10
4
5
10
4
5
10
4
5
1
1
2
1
1
2
2
8
9
2
8
9
3
5
6
4
2
3
4
2
3
4
2
3
[[1. 1. 2.]
 [2. 2. 1.]
 [1. 1. 2.]
 [2. 2. 3.]]
